### ISSUE TITLE
(property) VPhoneInput: unknown

### ISSUE THREAD

**Issue by IgorIlgiyaev** [paul-thebaud/v-phone-input#30] opened 2024-03-12 09:53 UTC
## Expected Behavior
To recognize the <v-phone-input />

## Actual Behavior
GET http://localhost:5173/node_modules/.vite/deps/v-phone-input.js?v=2a7ae817 net::ERR_ABORTED 504 (Outdated Optimize Dep)

## Steps to Reproduce the Problem
After Install and Import

## Specifications

  - OS: Ma Os
  - Browser: Chrome
  - Browser version: Latest
  - Package version: 4.1.2"
  - Vuetify version: 3.5.8

**Comment by paul-thebaud** [comment] 2024-03-12 10:43
@IgorIlgiyaev, looks like there is problem with your build. Without a minimal reproduction repo and further details, I cannot help with this...

**Comment by IgorIlgiyaev** [comment] 2024-03-12 11:49
Will check.

**Comment by paul-thebaud** [comment] 2024-03-12 13:26
Closing this since there is not reproductible issue for now. Feel free to open a new, clear and detailed issue.

**Closed by paul-thebaud** 2024-03-12 13:26 UTC
Labels: question
